package db.migration;

import com.speaive.blog.domain.PostRevisionEventType;
import org.commonmark.Extension;
import org.commonmark.ext.gfm.strikethrough.StrikethroughExtension;
import org.commonmark.ext.gfm.tables.TablesExtension;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.owasp.html.Encoding;
import org.owasp.html.HtmlPolicyBuilder;
import org.owasp.html.PolicyFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.regex.Pattern;

/**
 * Repairs values produced by the pre-V3 automatic description extractor.
 *
 * <p>The legacy schema did not persist whether a description was generated or entered manually. A manually entered
 * value that is byte-for-byte identical to the legacy extractor output is therefore indistinguishable and is treated
 * as generated by this migration.</p>
 */
public final class V3__Decode_numeric_entities_in_descriptions extends BaseJavaMigration {
    private static final int DESCRIPTION_LENGTH = 180;
    private static final Pattern HTML_TAG = Pattern.compile("<[^>]+>");
    private static final List<Extension> EXTENSIONS = List.of(
            TablesExtension.create(),
            StrikethroughExtension.create()
    );
    private static final Parser PARSER = Parser.builder().extensions(EXTENSIONS).build();
    private static final HtmlRenderer RENDERER = HtmlRenderer.builder()
            .extensions(EXTENSIONS)
            .escapeHtml(false)
            .build();
    private static final PolicyFactory HTML_POLICY = new HtmlPolicyBuilder()
            .allowElements("a", "blockquote", "br", "code", "del", "details", "em", "h1", "h2", "h3",
                    "h4", "h5", "h6", "hr", "img", "li", "ol", "p", "pre", "strong", "summary",
                    "table", "tbody", "td", "th", "thead", "tr", "ul")
            .allowAttributes("href", "title").onElements("a")
            .allowAttributes("class").matching(Pattern.compile("^language-[A-Za-z0-9_+.-]+$"))
            .onElements("code")
            .allowAttributes("src", "alt", "title", "loading").onElements("img")
            .allowUrlProtocols("http", "https", "mailto")
            .toFactory();

    @Override
    public void migrate(Context context) throws Exception {
        lockActivePosts(context.getConnection());
        Map<String, Map<String, String>> knownRepairs = repairPostRevisions(context.getConnection());
        repairPosts(context.getConnection(), knownRepairs);
    }

    private static void lockActivePosts(Connection connection) throws SQLException {
        try (PreparedStatement lock = connection.prepareStatement("SELECT id FROM blog_post FOR UPDATE");
             ResultSet rows = lock.executeQuery()) {
            while (rows.next()) {
                rows.getString("id");
            }
        }
    }

    private static Map<String, Map<String, String>> repairPostRevisions(Connection connection) throws Exception {
        Map<String, Map<String, String>> knownRepairs = new HashMap<>();
        try (PreparedStatement select = connection.prepareStatement("""
                SELECT post_id, revision, description, body
                FROM blog_post_revision
                ORDER BY post_id, revision
                FOR UPDATE
                """);
             PreparedStatement update = connection.prepareStatement("""
                UPDATE blog_post_revision
                SET description = ?
                WHERE post_id = ? AND revision = ? AND description = ? AND body = ?
                """);
             ResultSet rows = select.executeQuery()) {
            while (rows.next()) {
                String postId = rows.getString("post_id");
                String description = rows.getString("description");
                String body = rows.getString("body");
                Map<String, String> postRepairs = knownRepairs.computeIfAbsent(postId, ignored -> new HashMap<>());
                registerAutoDescription(postRepairs, description, body);

                String repaired = postRepairs.get(description);
                if (repaired != null && !repaired.equals(description)) {
                    update.setString(1, repaired);
                    update.setString(2, postId);
                    update.setLong(3, rows.getLong("revision"));
                    update.setString(4, description);
                    update.setString(5, body);
                    requireSingleRow(update.executeUpdate(), "blog_post_revision", postId);
                }
            }
        }
        return knownRepairs;
    }

    private static void repairPosts(
            Connection connection,
            Map<String, Map<String, String>> knownRepairs
    ) throws Exception {
        try (PreparedStatement select = connection.prepareStatement("""
                SELECT id, revision, description, body
                FROM blog_post
                FOR UPDATE
                """);
             PreparedStatement update = connection.prepareStatement("""
                UPDATE blog_post
                SET description = ?, revision = revision + 1
                WHERE id = ? AND revision = ? AND description = ? AND body = ?
                """);
             PreparedStatement insertRevision = connection.prepareStatement("""
                INSERT INTO blog_post_revision (
                    post_id, revision, slug, title, description, published_at, updated_at,
                    status, body, cover, post_created_at, event_type, recorded_at, author_id
                )
                SELECT id, revision, slug, title, description, published_at, updated_at,
                       status, body, cover, created_at, ?, CURRENT_TIMESTAMP, author_id
                FROM blog_post
                WHERE id = ? AND revision = ?
                """);
             PreparedStatement insertRevisionTags = connection.prepareStatement("""
                INSERT INTO blog_post_revision_tag (post_id, revision, tag_order, tag)
                SELECT post_id, ?, tag_order, tag
                FROM blog_post_tag
                WHERE post_id = ?
                """);
             ResultSet rows = select.executeQuery()) {
            while (rows.next()) {
                String postId = rows.getString("id");
                String description = rows.getString("description");
                String body = rows.getString("body");
                Map<String, String> postRepairs = knownRepairs.computeIfAbsent(postId, ignored -> new HashMap<>());
                registerAutoDescription(postRepairs, description, body);

                String repaired = postRepairs.get(description);
                if (repaired != null && !repaired.equals(description)) {
                    long currentRevision = rows.getLong("revision");
                    long repairedRevision = currentRevision + 1;
                    update.setString(1, repaired);
                    update.setString(2, postId);
                    update.setLong(3, currentRevision);
                    update.setString(4, description);
                    update.setString(5, body);
                    requireSingleRow(update.executeUpdate(), "blog_post", postId);

                    insertRevision.setString(1, PostRevisionEventType.UPDATE.name());
                    insertRevision.setString(2, postId);
                    insertRevision.setLong(3, repairedRevision);
                    requireSingleRow(insertRevision.executeUpdate(), "blog_post_revision", postId);

                    insertRevisionTags.setLong(1, repairedRevision);
                    insertRevisionTags.setString(2, postId);
                    insertRevisionTags.executeUpdate();
                }
            }
        }
    }

    private static void requireSingleRow(int updatedRows, String table, String postId) throws SQLException {
        if (updatedRows != 1) {
            throw new SQLException("Expected one " + table + " row for post " + postId + ", updated " + updatedRows);
        }
    }

    private static void registerAutoDescription(
            Map<String, String> postRepairs,
            String storedDescription,
            String body
    ) {
        DescriptionPair generated = extractDescriptions(body);
        if (storedDescription.equals(generated.legacy()) && !generated.legacy().equals(generated.repaired())) {
            postRepairs.put(generated.legacy(), generated.repaired());
        }
    }

    private static DescriptionPair extractDescriptions(String markdown) {
        // Freeze both sides of the extractor bug instead of depending on application code that can evolve later.
        String html = HTML_POLICY.sanitize(RENDERER.render(PARSER.parse(Objects.requireNonNullElse(markdown, ""))));
        String withoutTags = HTML_TAG.matcher(html).replaceAll(" ");
        String legacy = withoutTags
                .replace("&amp;", "&")
                .replace("&lt;", "<")
                .replace("&gt;", ">");
        String repaired = Encoding.decodeHtml(withoutTags, false);
        return new DescriptionPair(
                normalizeAndTruncate(legacy),
                normalizeAndTruncate(repaired)
        );
    }

    private static String normalizeAndTruncate(String value) {
        String plain = value.replaceAll("\\s+", " ").trim();
        if (plain.isEmpty()) {
            return "";
        }
        int codePoints = plain.codePointCount(0, plain.length());
        if (codePoints <= DESCRIPTION_LENGTH) {
            return plain;
        }
        int end = plain.offsetByCodePoints(0, DESCRIPTION_LENGTH - 3);
        return plain.substring(0, end).stripTrailing() + "...";
    }

    private record DescriptionPair(String legacy, String repaired) {
    }
}
