#!/bin/sh

configure_database_env() {
  SPEAIVE_DB_NAME=${SPEAIVE_DB_NAME:-speaive_blog}
  SPEAIVE_DB_USERNAME=${SPEAIVE_DB_USERNAME:-speaive}
  SPEAIVE_DB_HOST=${SPEAIVE_DB_HOST:-127.0.0.1}
  SPEAIVE_DB_PORT=${SPEAIVE_DB_PORT:-5432}

  if [ -z "${SPRING_DATASOURCE_PASSWORD:-}" ]; then
    : "${SPEAIVE_DB_PASSWORD:?请在 .env 中设置 SPEAIVE_DB_PASSWORD}"
    SPRING_DATASOURCE_PASSWORD=$SPEAIVE_DB_PASSWORD
  fi

  SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL:-jdbc:postgresql://$SPEAIVE_DB_HOST:$SPEAIVE_DB_PORT/$SPEAIVE_DB_NAME}
  SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-$SPEAIVE_DB_USERNAME}

  export SPRING_DATASOURCE_URL SPRING_DATASOURCE_USERNAME SPRING_DATASOURCE_PASSWORD
}
